# Generated by Django 4.0.6 on 2022-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
