# Generated by Django 4.0.6 on 2022-07-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_delete_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
