# Generated by Django 4.0.6 on 2022-07-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_hashtag_article_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ManyToManyField(related_name='hashtag', to='article.article')),
            ],
        ),
    ]
