# Generated by Django 4.0.6 on 2022-07-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_article_hashtags_article_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtag',
            table='hashtag',
        ),
    ]
